/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DocenteRouteImport } from './routes/docente'
import { Route as EstudianteRouteImport } from './routes/estudiante'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAsistenciasRouteImport } from './routes/admin.asistencias'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminDocentesRouteImport } from './routes/admin.docentes'
import { Route as AdminEstudiantesRouteImport } from './routes/admin.estudiantes'
import { Route as AdminInstitucionesRouteImport } from './routes/admin.instituciones'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminPracticasRouteImport } from './routes/admin.practicas'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as DocenteIndexRouteImport } from './routes/docente.index'
import { Route as DocenteAnecdotariosRouteImport } from './routes/docente.anecdotarios'
import { Route as DocenteAsistenciasRouteImport } from './routes/docente.asistencias'
import { Route as DocenteEvidenciasRouteImport } from './routes/docente.evidencias'
import { Route as DocenteMapaRouteImport } from './routes/docente.mapa'
import { Route as DocenteNotificacionesRouteImport } from './routes/docente.notificaciones'
import { Route as DocentePerfilRouteImport } from './routes/docente.perfil'
import { Route as DocenteReportesRouteImport } from './routes/docente.reportes'
import { Route as DocenteSeguimientoRouteImport } from './routes/docente.seguimiento'
import { Route as EstudianteIndexRouteImport } from './routes/estudiante.index'
import { Route as EstudianteAnecdotarioRouteImport } from './routes/estudiante.anecdotario'
import { Route as EstudianteAsistenciaRouteImport } from './routes/estudiante.asistencia'
import { Route as EstudianteAsistenteRouteImport } from './routes/estudiante.asistente'
import { Route as EstudianteCalendarioRouteImport } from './routes/estudiante.calendario'
import { Route as EstudianteEvidenciasRouteImport } from './routes/estudiante.evidencias'
import { Route as EstudianteMiPracticaRouteImport } from './routes/estudiante.mi-practica'
import { Route as EstudianteNotificacionesRouteImport } from './routes/estudiante.notificaciones'
import { Route as EstudiantePerfilRouteImport } from './routes/estudiante.perfil'
import { Route as EstudianteRegistrarAsistenciaRouteImport } from './routes/estudiante.registrar-asistencia'
import { Route as EstudianteRevisionIaRouteImport } from './routes/estudiante.revision-ia'
import { Route as EstudianteSesionesRouteImport } from './routes/estudiante.sesiones'
import { Route as DocenteEstudiantesIndexRouteImport } from './routes/docente.estudiantes.index'
import { Route as DocenteEstudiantesEstudianteIdRouteImport } from './routes/docente.estudiantes.$estudianteId'
import { Route as DocenteSesionesIndexRouteImport } from './routes/docente.sesiones.index'
import { Route as DocenteSesionesSesionIdRouteImport } from './routes/docente.sesiones.$sesionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteRoute = DocenteRouteImport.update({
  id: '/docente',
  path: '/docente',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteRoute = EstudianteRouteImport.update({
  id: '/estudiante',
  path: '/estudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAsistenciasRoute = AdminAsistenciasRouteImport.update({
  id: '/asistencias',
  path: '/asistencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocentesRoute = AdminDocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstudiantesRoute = AdminEstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitucionesRoute = AdminInstitucionesRouteImport.update({
  id: '/instituciones',
  path: '/instituciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPracticasRoute = AdminPracticasRouteImport.update({
  id: '/practicas',
  path: '/practicas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const DocenteIndexRoute = DocenteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteAnecdotariosRoute = DocenteAnecdotariosRouteImport.update({
  id: '/anecdotarios',
  path: '/anecdotarios',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteAsistenciasRoute = DocenteAsistenciasRouteImport.update({
  id: '/asistencias',
  path: '/asistencias',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteEvidenciasRoute = DocenteEvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteMapaRoute = DocenteMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteNotificacionesRoute = DocenteNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => DocenteRoute,
} as any)
const DocentePerfilRoute = DocentePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteReportesRoute = DocenteReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteSeguimientoRoute = DocenteSeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => DocenteRoute,
} as any)
const EstudianteIndexRoute = EstudianteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteAnecdotarioRoute = EstudianteAnecdotarioRouteImport.update({
  id: '/anecdotario',
  path: '/anecdotario',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteAsistenciaRoute = EstudianteAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteAsistenteRoute = EstudianteAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteCalendarioRoute = EstudianteCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteEvidenciasRoute = EstudianteEvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteMiPracticaRoute = EstudianteMiPracticaRouteImport.update({
  id: '/mi-practica',
  path: '/mi-practica',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteNotificacionesRoute =
  EstudianteNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => EstudianteRoute,
  } as any)
const EstudiantePerfilRoute = EstudiantePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteRegistrarAsistenciaRoute =
  EstudianteRegistrarAsistenciaRouteImport.update({
    id: '/registrar-asistencia',
    path: '/registrar-asistencia',
    getParentRoute: () => EstudianteRoute,
  } as any)
const EstudianteRevisionIaRoute = EstudianteRevisionIaRouteImport.update({
  id: '/revision-ia',
  path: '/revision-ia',
  getParentRoute: () => EstudianteRoute,
} as any)
const EstudianteSesionesRoute = EstudianteSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => EstudianteRoute,
} as any)
const DocenteEstudiantesIndexRoute = DocenteEstudiantesIndexRouteImport.update({
  id: '/estudiantes/',
  path: '/estudiantes/',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteEstudiantesEstudianteIdRoute =
  DocenteEstudiantesEstudianteIdRouteImport.update({
    id: '/estudiantes/$estudianteId',
    path: '/estudiantes/$estudianteId',
    getParentRoute: () => DocenteRoute,
  } as any)
const DocenteSesionesIndexRoute = DocenteSesionesIndexRouteImport.update({
  id: '/sesiones/',
  path: '/sesiones/',
  getParentRoute: () => DocenteRoute,
} as any)
const DocenteSesionesSesionIdRoute = DocenteSesionesSesionIdRouteImport.update({
  id: '/sesiones/$sesionId',
  path: '/sesiones/$sesionId',
  getParentRoute: () => DocenteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docente': typeof DocenteRouteWithChildren
  '/estudiante': typeof EstudianteRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/admin/asistencias': typeof AdminAsistenciasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/docentes': typeof AdminDocentesRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/instituciones': typeof AdminInstitucionesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/anecdotarios': typeof DocenteAnecdotariosRoute
  '/docente/asistencias': typeof DocenteAsistenciasRoute
  '/docente/evidencias': typeof DocenteEvidenciasRoute
  '/docente/mapa': typeof DocenteMapaRoute
  '/docente/notificaciones': typeof DocenteNotificacionesRoute
  '/docente/perfil': typeof DocentePerfilRoute
  '/docente/reportes': typeof DocenteReportesRoute
  '/docente/seguimiento': typeof DocenteSeguimientoRoute
  '/estudiante/anecdotario': typeof EstudianteAnecdotarioRoute
  '/estudiante/asistencia': typeof EstudianteAsistenciaRoute
  '/estudiante/asistente': typeof EstudianteAsistenteRoute
  '/estudiante/calendario': typeof EstudianteCalendarioRoute
  '/estudiante/evidencias': typeof EstudianteEvidenciasRoute
  '/estudiante/mi-practica': typeof EstudianteMiPracticaRoute
  '/estudiante/notificaciones': typeof EstudianteNotificacionesRoute
  '/estudiante/perfil': typeof EstudiantePerfilRoute
  '/estudiante/registrar-asistencia': typeof EstudianteRegistrarAsistenciaRoute
  '/estudiante/revision-ia': typeof EstudianteRevisionIaRoute
  '/estudiante/sesiones': typeof EstudianteSesionesRoute
  '/admin/': typeof AdminIndexRoute
  '/docente/': typeof DocenteIndexRoute
  '/estudiante/': typeof EstudianteIndexRoute
  '/docente/estudiantes/$estudianteId': typeof DocenteEstudiantesEstudianteIdRoute
  '/docente/sesiones/$sesionId': typeof DocenteSesionesSesionIdRoute
  '/docente/estudiantes/': typeof DocenteEstudiantesIndexRoute
  '/docente/sesiones/': typeof DocenteSesionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/admin/asistencias': typeof AdminAsistenciasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/docentes': typeof AdminDocentesRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/instituciones': typeof AdminInstitucionesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/anecdotarios': typeof DocenteAnecdotariosRoute
  '/docente/asistencias': typeof DocenteAsistenciasRoute
  '/docente/evidencias': typeof DocenteEvidenciasRoute
  '/docente/mapa': typeof DocenteMapaRoute
  '/docente/notificaciones': typeof DocenteNotificacionesRoute
  '/docente/perfil': typeof DocentePerfilRoute
  '/docente/reportes': typeof DocenteReportesRoute
  '/docente/seguimiento': typeof DocenteSeguimientoRoute
  '/estudiante/anecdotario': typeof EstudianteAnecdotarioRoute
  '/estudiante/asistencia': typeof EstudianteAsistenciaRoute
  '/estudiante/asistente': typeof EstudianteAsistenteRoute
  '/estudiante/calendario': typeof EstudianteCalendarioRoute
  '/estudiante/evidencias': typeof EstudianteEvidenciasRoute
  '/estudiante/mi-practica': typeof EstudianteMiPracticaRoute
  '/estudiante/notificaciones': typeof EstudianteNotificacionesRoute
  '/estudiante/perfil': typeof EstudiantePerfilRoute
  '/estudiante/registrar-asistencia': typeof EstudianteRegistrarAsistenciaRoute
  '/estudiante/revision-ia': typeof EstudianteRevisionIaRoute
  '/estudiante/sesiones': typeof EstudianteSesionesRoute
  '/admin': typeof AdminIndexRoute
  '/docente': typeof DocenteIndexRoute
  '/estudiante': typeof EstudianteIndexRoute
  '/docente/estudiantes/$estudianteId': typeof DocenteEstudiantesEstudianteIdRoute
  '/docente/sesiones/$sesionId': typeof DocenteSesionesSesionIdRoute
  '/docente/estudiantes': typeof DocenteEstudiantesIndexRoute
  '/docente/sesiones': typeof DocenteSesionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docente': typeof DocenteRouteWithChildren
  '/estudiante': typeof EstudianteRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/admin/asistencias': typeof AdminAsistenciasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/docentes': typeof AdminDocentesRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/instituciones': typeof AdminInstitucionesRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/anecdotarios': typeof DocenteAnecdotariosRoute
  '/docente/asistencias': typeof DocenteAsistenciasRoute
  '/docente/evidencias': typeof DocenteEvidenciasRoute
  '/docente/mapa': typeof DocenteMapaRoute
  '/docente/notificaciones': typeof DocenteNotificacionesRoute
  '/docente/perfil': typeof DocentePerfilRoute
  '/docente/reportes': typeof DocenteReportesRoute
  '/docente/seguimiento': typeof DocenteSeguimientoRoute
  '/estudiante/anecdotario': typeof EstudianteAnecdotarioRoute
  '/estudiante/asistencia': typeof EstudianteAsistenciaRoute
  '/estudiante/asistente': typeof EstudianteAsistenteRoute
  '/estudiante/calendario': typeof EstudianteCalendarioRoute
  '/estudiante/evidencias': typeof EstudianteEvidenciasRoute
  '/estudiante/mi-practica': typeof EstudianteMiPracticaRoute
  '/estudiante/notificaciones': typeof EstudianteNotificacionesRoute
  '/estudiante/perfil': typeof EstudiantePerfilRoute
  '/estudiante/registrar-asistencia': typeof EstudianteRegistrarAsistenciaRoute
  '/estudiante/revision-ia': typeof EstudianteRevisionIaRoute
  '/estudiante/sesiones': typeof EstudianteSesionesRoute
  '/admin/': typeof AdminIndexRoute
  '/docente/': typeof DocenteIndexRoute
  '/estudiante/': typeof EstudianteIndexRoute
  '/docente/estudiantes/$estudianteId': typeof DocenteEstudiantesEstudianteIdRoute
  '/docente/sesiones/$sesionId': typeof DocenteSesionesSesionIdRoute
  '/docente/estudiantes/': typeof DocenteEstudiantesIndexRoute
  '/docente/sesiones/': typeof DocenteSesionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/docente'
    | '/estudiante'
    | '/recuperar-contrasena'
    | '/admin/asistencias'
    | '/admin/configuracion'
    | '/admin/docentes'
    | '/admin/estudiantes'
    | '/admin/instituciones'
    | '/admin/perfil'
    | '/admin/practicas'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/anecdotarios'
    | '/docente/asistencias'
    | '/docente/evidencias'
    | '/docente/mapa'
    | '/docente/notificaciones'
    | '/docente/perfil'
    | '/docente/reportes'
    | '/docente/seguimiento'
    | '/estudiante/anecdotario'
    | '/estudiante/asistencia'
    | '/estudiante/asistente'
    | '/estudiante/calendario'
    | '/estudiante/evidencias'
    | '/estudiante/mi-practica'
    | '/estudiante/notificaciones'
    | '/estudiante/perfil'
    | '/estudiante/registrar-asistencia'
    | '/estudiante/revision-ia'
    | '/estudiante/sesiones'
    | '/admin/'
    | '/docente/'
    | '/estudiante/'
    | '/docente/estudiantes/$estudianteId'
    | '/docente/sesiones/$sesionId'
    | '/docente/estudiantes/'
    | '/docente/sesiones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recuperar-contrasena'
    | '/admin/asistencias'
    | '/admin/configuracion'
    | '/admin/docentes'
    | '/admin/estudiantes'
    | '/admin/instituciones'
    | '/admin/perfil'
    | '/admin/practicas'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/anecdotarios'
    | '/docente/asistencias'
    | '/docente/evidencias'
    | '/docente/mapa'
    | '/docente/notificaciones'
    | '/docente/perfil'
    | '/docente/reportes'
    | '/docente/seguimiento'
    | '/estudiante/anecdotario'
    | '/estudiante/asistencia'
    | '/estudiante/asistente'
    | '/estudiante/calendario'
    | '/estudiante/evidencias'
    | '/estudiante/mi-practica'
    | '/estudiante/notificaciones'
    | '/estudiante/perfil'
    | '/estudiante/registrar-asistencia'
    | '/estudiante/revision-ia'
    | '/estudiante/sesiones'
    | '/admin'
    | '/docente'
    | '/estudiante'
    | '/docente/estudiantes/$estudianteId'
    | '/docente/sesiones/$sesionId'
    | '/docente/estudiantes'
    | '/docente/sesiones'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/docente'
    | '/estudiante'
    | '/recuperar-contrasena'
    | '/admin/asistencias'
    | '/admin/configuracion'
    | '/admin/docentes'
    | '/admin/estudiantes'
    | '/admin/instituciones'
    | '/admin/perfil'
    | '/admin/practicas'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/anecdotarios'
    | '/docente/asistencias'
    | '/docente/evidencias'
    | '/docente/mapa'
    | '/docente/notificaciones'
    | '/docente/perfil'
    | '/docente/reportes'
    | '/docente/seguimiento'
    | '/estudiante/anecdotario'
    | '/estudiante/asistencia'
    | '/estudiante/asistente'
    | '/estudiante/calendario'
    | '/estudiante/evidencias'
    | '/estudiante/mi-practica'
    | '/estudiante/notificaciones'
    | '/estudiante/perfil'
    | '/estudiante/registrar-asistencia'
    | '/estudiante/revision-ia'
    | '/estudiante/sesiones'
    | '/admin/'
    | '/docente/'
    | '/estudiante/'
    | '/docente/estudiantes/$estudianteId'
    | '/docente/sesiones/$sesionId'
    | '/docente/estudiantes/'
    | '/docente/sesiones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocenteRoute: typeof DocenteRouteWithChildren
  EstudianteRoute: typeof EstudianteRouteWithChildren
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente': {
      id: '/docente'
      path: '/docente'
      fullPath: '/docente'
      preLoaderRoute: typeof DocenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante': {
      id: '/estudiante'
      path: '/estudiante'
      fullPath: '/estudiante'
      preLoaderRoute: typeof EstudianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/asistencias': {
      id: '/admin/asistencias'
      path: '/asistencias'
      fullPath: '/admin/asistencias'
      preLoaderRoute: typeof AdminAsistenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docentes': {
      id: '/admin/docentes'
      path: '/docentes'
      fullPath: '/admin/docentes'
      preLoaderRoute: typeof AdminDocentesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estudiantes': {
      id: '/admin/estudiantes'
      path: '/estudiantes'
      fullPath: '/admin/estudiantes'
      preLoaderRoute: typeof AdminEstudiantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instituciones': {
      id: '/admin/instituciones'
      path: '/instituciones'
      fullPath: '/admin/instituciones'
      preLoaderRoute: typeof AdminInstitucionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/practicas': {
      id: '/admin/practicas'
      path: '/practicas'
      fullPath: '/admin/practicas'
      preLoaderRoute: typeof AdminPracticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docente/': {
      id: '/docente/'
      path: '/'
      fullPath: '/docente/'
      preLoaderRoute: typeof DocenteIndexRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/anecdotarios': {
      id: '/docente/anecdotarios'
      path: '/anecdotarios'
      fullPath: '/docente/anecdotarios'
      preLoaderRoute: typeof DocenteAnecdotariosRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/asistencias': {
      id: '/docente/asistencias'
      path: '/asistencias'
      fullPath: '/docente/asistencias'
      preLoaderRoute: typeof DocenteAsistenciasRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/evidencias': {
      id: '/docente/evidencias'
      path: '/evidencias'
      fullPath: '/docente/evidencias'
      preLoaderRoute: typeof DocenteEvidenciasRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/mapa': {
      id: '/docente/mapa'
      path: '/mapa'
      fullPath: '/docente/mapa'
      preLoaderRoute: typeof DocenteMapaRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/notificaciones': {
      id: '/docente/notificaciones'
      path: '/notificaciones'
      fullPath: '/docente/notificaciones'
      preLoaderRoute: typeof DocenteNotificacionesRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/perfil': {
      id: '/docente/perfil'
      path: '/perfil'
      fullPath: '/docente/perfil'
      preLoaderRoute: typeof DocentePerfilRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/reportes': {
      id: '/docente/reportes'
      path: '/reportes'
      fullPath: '/docente/reportes'
      preLoaderRoute: typeof DocenteReportesRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/seguimiento': {
      id: '/docente/seguimiento'
      path: '/seguimiento'
      fullPath: '/docente/seguimiento'
      preLoaderRoute: typeof DocenteSeguimientoRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/estudiante/': {
      id: '/estudiante/'
      path: '/'
      fullPath: '/estudiante/'
      preLoaderRoute: typeof EstudianteIndexRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/anecdotario': {
      id: '/estudiante/anecdotario'
      path: '/anecdotario'
      fullPath: '/estudiante/anecdotario'
      preLoaderRoute: typeof EstudianteAnecdotarioRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/asistencia': {
      id: '/estudiante/asistencia'
      path: '/asistencia'
      fullPath: '/estudiante/asistencia'
      preLoaderRoute: typeof EstudianteAsistenciaRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/asistente': {
      id: '/estudiante/asistente'
      path: '/asistente'
      fullPath: '/estudiante/asistente'
      preLoaderRoute: typeof EstudianteAsistenteRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/calendario': {
      id: '/estudiante/calendario'
      path: '/calendario'
      fullPath: '/estudiante/calendario'
      preLoaderRoute: typeof EstudianteCalendarioRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/evidencias': {
      id: '/estudiante/evidencias'
      path: '/evidencias'
      fullPath: '/estudiante/evidencias'
      preLoaderRoute: typeof EstudianteEvidenciasRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/mi-practica': {
      id: '/estudiante/mi-practica'
      path: '/mi-practica'
      fullPath: '/estudiante/mi-practica'
      preLoaderRoute: typeof EstudianteMiPracticaRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/notificaciones': {
      id: '/estudiante/notificaciones'
      path: '/notificaciones'
      fullPath: '/estudiante/notificaciones'
      preLoaderRoute: typeof EstudianteNotificacionesRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/perfil': {
      id: '/estudiante/perfil'
      path: '/perfil'
      fullPath: '/estudiante/perfil'
      preLoaderRoute: typeof EstudiantePerfilRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/registrar-asistencia': {
      id: '/estudiante/registrar-asistencia'
      path: '/registrar-asistencia'
      fullPath: '/estudiante/registrar-asistencia'
      preLoaderRoute: typeof EstudianteRegistrarAsistenciaRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/revision-ia': {
      id: '/estudiante/revision-ia'
      path: '/revision-ia'
      fullPath: '/estudiante/revision-ia'
      preLoaderRoute: typeof EstudianteRevisionIaRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/estudiante/sesiones': {
      id: '/estudiante/sesiones'
      path: '/sesiones'
      fullPath: '/estudiante/sesiones'
      preLoaderRoute: typeof EstudianteSesionesRouteImport
      parentRoute: typeof EstudianteRoute
    }
    '/docente/estudiantes/': {
      id: '/docente/estudiantes/'
      path: '/estudiantes'
      fullPath: '/docente/estudiantes/'
      preLoaderRoute: typeof DocenteEstudiantesIndexRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/estudiantes/$estudianteId': {
      id: '/docente/estudiantes/$estudianteId'
      path: '/estudiantes/$estudianteId'
      fullPath: '/docente/estudiantes/$estudianteId'
      preLoaderRoute: typeof DocenteEstudiantesEstudianteIdRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/sesiones/': {
      id: '/docente/sesiones/'
      path: '/sesiones'
      fullPath: '/docente/sesiones/'
      preLoaderRoute: typeof DocenteSesionesIndexRouteImport
      parentRoute: typeof DocenteRoute
    }
    '/docente/sesiones/$sesionId': {
      id: '/docente/sesiones/$sesionId'
      path: '/sesiones/$sesionId'
      fullPath: '/docente/sesiones/$sesionId'
      preLoaderRoute: typeof DocenteSesionesSesionIdRouteImport
      parentRoute: typeof DocenteRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAsistenciasRoute: typeof AdminAsistenciasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDocentesRoute: typeof AdminDocentesRoute
  AdminEstudiantesRoute: typeof AdminEstudiantesRoute
  AdminInstitucionesRoute: typeof AdminInstitucionesRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminPracticasRoute: typeof AdminPracticasRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAsistenciasRoute: AdminAsistenciasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDocentesRoute: AdminDocentesRoute,
  AdminEstudiantesRoute: AdminEstudiantesRoute,
  AdminInstitucionesRoute: AdminInstitucionesRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminPracticasRoute: AdminPracticasRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocenteRouteChildren {
  DocenteAnecdotariosRoute: typeof DocenteAnecdotariosRoute
  DocenteAsistenciasRoute: typeof DocenteAsistenciasRoute
  DocenteEvidenciasRoute: typeof DocenteEvidenciasRoute
  DocenteMapaRoute: typeof DocenteMapaRoute
  DocenteNotificacionesRoute: typeof DocenteNotificacionesRoute
  DocentePerfilRoute: typeof DocentePerfilRoute
  DocenteReportesRoute: typeof DocenteReportesRoute
  DocenteSeguimientoRoute: typeof DocenteSeguimientoRoute
  DocenteIndexRoute: typeof DocenteIndexRoute
  DocenteEstudiantesEstudianteIdRoute: typeof DocenteEstudiantesEstudianteIdRoute
  DocenteSesionesSesionIdRoute: typeof DocenteSesionesSesionIdRoute
  DocenteEstudiantesIndexRoute: typeof DocenteEstudiantesIndexRoute
  DocenteSesionesIndexRoute: typeof DocenteSesionesIndexRoute
}

const DocenteRouteChildren: DocenteRouteChildren = {
  DocenteAnecdotariosRoute: DocenteAnecdotariosRoute,
  DocenteAsistenciasRoute: DocenteAsistenciasRoute,
  DocenteEvidenciasRoute: DocenteEvidenciasRoute,
  DocenteMapaRoute: DocenteMapaRoute,
  DocenteNotificacionesRoute: DocenteNotificacionesRoute,
  DocentePerfilRoute: DocentePerfilRoute,
  DocenteReportesRoute: DocenteReportesRoute,
  DocenteSeguimientoRoute: DocenteSeguimientoRoute,
  DocenteIndexRoute: DocenteIndexRoute,
  DocenteEstudiantesEstudianteIdRoute: DocenteEstudiantesEstudianteIdRoute,
  DocenteSesionesSesionIdRoute: DocenteSesionesSesionIdRoute,
  DocenteEstudiantesIndexRoute: DocenteEstudiantesIndexRoute,
  DocenteSesionesIndexRoute: DocenteSesionesIndexRoute,
}

const DocenteRouteWithChildren =
  DocenteRoute._addFileChildren(DocenteRouteChildren)

interface EstudianteRouteChildren {
  EstudianteAnecdotarioRoute: typeof EstudianteAnecdotarioRoute
  EstudianteAsistenciaRoute: typeof EstudianteAsistenciaRoute
  EstudianteAsistenteRoute: typeof EstudianteAsistenteRoute
  EstudianteCalendarioRoute: typeof EstudianteCalendarioRoute
  EstudianteEvidenciasRoute: typeof EstudianteEvidenciasRoute
  EstudianteMiPracticaRoute: typeof EstudianteMiPracticaRoute
  EstudianteNotificacionesRoute: typeof EstudianteNotificacionesRoute
  EstudiantePerfilRoute: typeof EstudiantePerfilRoute
  EstudianteRegistrarAsistenciaRoute: typeof EstudianteRegistrarAsistenciaRoute
  EstudianteRevisionIaRoute: typeof EstudianteRevisionIaRoute
  EstudianteSesionesRoute: typeof EstudianteSesionesRoute
  EstudianteIndexRoute: typeof EstudianteIndexRoute
}

const EstudianteRouteChildren: EstudianteRouteChildren = {
  EstudianteAnecdotarioRoute: EstudianteAnecdotarioRoute,
  EstudianteAsistenciaRoute: EstudianteAsistenciaRoute,
  EstudianteAsistenteRoute: EstudianteAsistenteRoute,
  EstudianteCalendarioRoute: EstudianteCalendarioRoute,
  EstudianteEvidenciasRoute: EstudianteEvidenciasRoute,
  EstudianteMiPracticaRoute: EstudianteMiPracticaRoute,
  EstudianteNotificacionesRoute: EstudianteNotificacionesRoute,
  EstudiantePerfilRoute: EstudiantePerfilRoute,
  EstudianteRegistrarAsistenciaRoute: EstudianteRegistrarAsistenciaRoute,
  EstudianteRevisionIaRoute: EstudianteRevisionIaRoute,
  EstudianteSesionesRoute: EstudianteSesionesRoute,
  EstudianteIndexRoute: EstudianteIndexRoute,
}

const EstudianteRouteWithChildren = EstudianteRoute._addFileChildren(
  EstudianteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DocenteRoute: DocenteRouteWithChildren,
  EstudianteRoute: EstudianteRouteWithChildren,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
